import numpy as np

def read_Cp(filename, headerLines=3):
    """ reads a pressure coefficient file generated by xfoil """
    data = np.loadtxt(filename, skiprows=3, usecols=(0, 1, 2))
    x  = data[:, 0]          # x/c
    y  = data[:, 1]          # y/c (useful for checking geometry)
    Cp = data[:, 2]          # pressure coefficient
    return x, y, Cp


def read_polar(filename, headerLines=12):
    """ reads a polar generated by xfoil """
    data = np.loadtxt(filename, skiprows=headerLines, usecols=(0, 1, 2, 4), comments=None, unpack=True )
    alphas, cls, cds, cms = data[0], data[1], data[2], data[3]

    # Sort by angle of attack
    sort_idx = np.argsort(alphas)
    alphas = alphas[sort_idx]
    cls    = cls[sort_idx]
    cds    = cds[sort_idx]
    cms    = cms[sort_idx]
    
    return alphas, cls, cds, cms
